### PR TITLE
Keyboard issues

### LINKED ISSUE #104: Line under account name input field and Continue button can disappear
**Bug Description**
When making a new account and entering a name for it, the line under the input field will disappear below the keyboard, if you go forward and then back again. It might be good to put both the button and line above the keyboard. This is likely related to the removed dependency during the update to the iOS 15 SDK. 

image

**Steps to Reproduce**
- Start making a new account
- Enter a name for the account
- Go forward one page, and then go back again. 
- Notice how the line under the input field has appeared, and the Continue button is also nowhere to be seen.

**Expected Result**
- Both the line and the button stays above the keyboard.

**Actual Result**
- The line and the button seems to be hidden behind the keyboard.

**Versions**
- Software Version: 1.0(22)
- OS: iOS 14.7 and 15

### LINKED ISSUE #106: "Add memo to transfer" button hidden behind keyboard.
**Bug Description**
When adding a memo to a transaction, the button is hidden behind the keyboard. Pressing enter just adds new lines, so it is hard to see how to “get out” of the text field. The button should stay above the keyboard, so it can be seen at all times.

image

**Steps to Reproduce**
- Try to add a memo to a transaction.
- Notice how the button cannot be seen when the keyboard is up, and how pressing Return will just add newlines.

**Expected Result**
- Button is shown
- Return adds new lines to the memo

**Actual Result**
- Button is not shown
- Return adds new lines to the memo as intended.

**Versions**
- Software Version: 1.0(22)
- OS: iOS

### PR DESCRIPTION
**Pull request by kristiyandobrev**
## Purpose

Fixed various keyboard issues and streamlined the dismissal of the keyboard. 

| Screenshot 2021-11-16 at 11 00 14 | Screenshot 2021-11-16 at 11 00 29  |  Screenshot 2021-11-16 at 11 00 48  |
|---|---|---|
| Screenshot 2021-11-16 at 11 18 16  | Screenshot 2021-11-16 at 11 22 24  | Screenshot 2021-11-16 at 12 21 20  |

* Closes #104 
* Closes #106 

## Changes

* Introduced more streamlined approach for handling keyboard show and hide events. 
* Minimal spacing on top of the keyboard across all places where keyboard pushes UI content up.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

### CODE REVIEW

**Comment by kristiyandobrev** [comment]
@jens-concordium 

See the screenshots above ☝️

**Comment by td202** [comment]
image

When the display is set to zoomed, the keyboard still hides the "Next" button (iPhone SE2).

**Comment by kristiyandobrev** [comment]
> image
> 
> When the display is set to zoomed, the keyboard still hides the "Next" button (iPhone SE2).

I would say that is rather a design problem than a bug. The app doesn't really take ANY accessibility into account. Just a few examples that there are several bugs across the app when the display is set to "zoomed": 

|  Zoom In | Standart   |
|---|---|
| Screenshot 2021-11-17 at 14 37 45   |  Screenshot 2021-11-17 at 14 36 43  |

@jens-concordium ☝️

**Comment by jens-concordium** [comment]
@kristiyandobrev @td202 

Yeah, that's likely something that needs to be addressed in the design. I guess we have to skip fixing it for now, as it would probably require a large overhaul of the app to get it right everywhere, as Kristiyan mentions.

**Review by td202 — APPROVED** [review]

**Comment by jens-concordium** [comment]
@kristiyandobrev, @concordium-cl 

This works as intended in iOS 15 now. @concordium-cl, can you check iOS 14?

**Comment by concordium-cl** [comment]
Checked in 14.7.1, iphone11, v1.0.25. Looks goods. (It's a bit hard to keep track where the changes were made, but I checked what I could figure.)

**Pull request merged**
