### PR TITLE
Improvements after release

### PR DESCRIPTION
**Pull request by dkrmjolner**
## Task solved in this PR:
- #2 
- #4 
- #8 
- #22 
- Refactoring to remove warnings
- Deployment now points to new App Store Connect account

### CODE REVIEW

**Comment by abizjak** [comment]
Could you list the issues that were resolved by these changes in the pull request description?

**Comment by dkrmjolner** [comment]
@abizjak I've updated the description now.

**Comment by abizjak** [comment]
> @abizjak I've updated the description now.

Can you also clean up the description and either remove the parts that are not relevant, or update the placeholders so that they are meaningful.

**Comment by dkrmjolner** [comment]
@abizjak How about now?

**Comment by abizjak** [comment]
Great!

**Pull request merged**
